### ISSUE TITLE
FFmpeg fails to play videos OS-X 

### ISSUE THREAD

**Issue by Optimusprimeums** [UniversalMediaServer/UniversalMediaServer#468]
Issue on OS-X with FFmpeg versions bundled in UMS above 4.2.0
Works fine with FFmpeg from 4.1.3 (FFmpeg version g7cf1f0f) 
Video's are forced to transcode with FFmpeg, with the error in 4.2.0 and above happening below:

DEBUG 19:13:43.652 [ffmpeg-11] Reading pipe: /var/folders/4t/g5kvbxzj08vd4ys6hz58sy600000gn/T/universalmediaserver/ffmpegvideo_309_1422231223320
DEBUG 19:13:43.686 [ffmpeg-11-2] dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
DEBUG 19:13:43.686 [ffmpeg-11-2]   Referenced from: /Volumes/ums-5.0.0-distribution/Universal Media Server.app/Contents/Resources/Java/osx/ffmpeg
DEBUG 19:13:43.686 [ffmpeg-11-2]   Expected in: /usr/lib/libSystem.B.dylib
DEBUG 19:13:43.686 [ffmpeg-11-2] 
DEBUG 19:13:43.686 [ffmpeg-11-2] dyld: Symbol not found: ___sincos_stret
DEBUG 19:13:43.686 [ffmpeg-11-2]   Referenced from: /Volumes/ums-5.0.0-distribution/Universal Media Server.app/Contents/Resources/Java/osx/ffmpeg
DEBUG 19:13:43.686 [ffmpeg-11-2]   Expected in: /usr/lib/libSystem.B.dylib
DEBUG 19:13:43.686 [ffmpeg-11-2]

**Comment by Optimusprimeums** [comment]
@SubJunk Do you build FFmpeg yourself for UMS?

**Comment by SubJunk** [comment]
@Optimusprimeums nope, I get them from http://www.evermeet.cx/ffmpeg/snapshots/
If you can find a version of that that fixes the issue I'll be happy to update

**Comment by Optimusprimeums** [comment]
Sweet @SubJunk i'll do some more testing and see how we go

**Comment by SubJunk** [comment]
@Optimusprimeums very cool! we can do the 5.0.1 release straight after that since that seems like an important bug

**Comment by Sami32** [comment]
@Optimusprimeums @SubJunk So, did the FFmpeg latest version fixed this issue ?
